import { ThemeProvider } from "next-themes";
import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "VDI Management Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
